apiVersion: v1
kind: Service
metadata:
  name: {{ include "remco-webapp-chart.fullname" . }}
  labels:
    app: {{ include "remco-webapp-chart.name" . }}
    env: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "remco-webapp-chart.name" . }}
